name: Run Tests

on:
  # allows running workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  main:
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install NuclearBoy
        run: |
          ./install-nuclear-boy -d /home/runner/work -e nuclear-boy -g /home/runner/work/nuclear-boy/G4Data -c /home/runner/work/nuclear-boy/CrossSection
