name: Run Build and Test

on:
  # allows running workflows manually
  workflow_dispatch:

  push:
    branches:
      - develop
    paths:
      - '.github/workflows/run_build_and_test.yml'
      - 'install-nuclear-boy.sh'
      - 'tests/**'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          build-mount-path: ~/
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-docker-images: 'true'
          remove-codeql: 'true'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install NuclearBoy
        run: |
          ./install-nuclear-boy.sh -d ~/ \
            -e nuclear-boy \
            -g ~/nuclear-boy/G4Data \
            -c ~/nuclear-boy/CrossSection
      
      - name: Available disk space
        run: df -h

      - name: Run tests
        run: |
          source ~/nuclear-boy/nuclear-boy
          nuclear-boy activate
          python -m pip install pytest
          python -m pytest -ra tests