name: Run Tests

on:
  # allows running workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install NuclearBoy
        run: |
          ./install-nuclear-boy.sh -d ~/ \
            -e nuclear-boy \
            -g ~/nuclear-boy/G4Data \
            -c ~/nuclear-boy/CrossSection
